---

excludes:
  paths:
    - pattern: ".github/CODE_OF_CONDUCT.md"
      reason: "DOCUMENTATION_OF"
      comment: "Project OSS Contributor Covenant Code of Conduct. The CC-BY-SA-4.0 license applies to the CoC document text itself, not to the project source code. Not part of release artifacts."
