name: Codecov

on:
  workflow_call:
    inputs:
      coverage-command:
        description: 'The command to use to run the tests (defaults to go test -v -race -covermode=atomic -coverpkg=./...)'
        required: false
        type: string
        default: go test -v -race -covermode=atomic -coverpkg=./...
      coverage-output-file:
        description: 'The output file name to store the coverage results in (defaults to coverage.out)'
        required: false
        type: string
        default: coverage.out
      coverage-scope:
        description: 'The location to run the command on (defaults to ./...)'
        required: false
        type: string
        default: ./...
      disable_search:
        description: 'Disable search for coverage files. This is helpful when specifying what files you want to upload with the files option.'
        required: false
        type: string
        default: 'false'
    secrets:
      codecov:
        required: true

permissions: {}

jobs:
  Coverage:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8a09271fed8277ab7fb02dbb5917c8d0e78323b4
        with:
          egress-policy: block
          allowed-endpoints: >
              github.com:443
              golang.org:443
              keybase.io:443
              objects.githubusercontent.com:443
              proxy.golang.org:443
              storage.googleapis.com:443
              sum.golang.org:443
              api.codecov.io:443
              cli.codecov.io:443
              ingest.codecov.io:443

      - name: Init go
        uses: bytemare/actions/init-go@981f181f7b5b37944a59e3e1e68d18bbc4049cd3

      - name: Code Coverage
        shell: bash
        run: ${{ inputs.coverage-command }} -coverprofile=${{ inputs.coverage-output-file }} ${{ inputs.coverage-scope }}

      - uses: codecov/codecov-action@3440e5ef70c638a9f44602a80ab017feee1309fe
        env:
          CODECOV_TOKEN: ${{ secrets.codecov }}
        with:
          files: ${{ inputs.coverage-output-file }}
          disable_search: ${{ inputs.disable_search }}
