name: "Go Coverage"

on:
  workflow_call:
    inputs:
      go-mod:
        description: 'Go mod file'
        required: false
        type: string
        default: ./go.mod
      command:
        description: 'The command to use to run the coverage (e.g. go test -cover...)'
        required: false
        type: string
        default: go test -v -race -covermode=atomic -coverpkg=./...
      output-file:
        description: 'The output file name to store the coverage results in (defaults to .github/coverage.out)'
        required: false
        type: string
        default: .github/coverage.out
      scope:
        description: 'The location to run the command on (defaults to ./...)'
        required: false
        type: string
        default: ./...
    outputs:
      coverage-output-artefact:
        description: 'The name of the artefact to download the code coverage report from'
        value: code-coverage-report
      coverage-output-file:
        description: "Filename of the output coverage report."
        value: ${{ inputs.output-file }}

permissions: {}

jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443
            uploads.github.com:443

      - uses: bytemare/actions/init-go@2d4d80eaca06e8ee8a7c212ad7ad55b8b0b801fd
        with:
          go-mod: ${{ inputs.go-mod }}

      - name: Run coverage
        id: cover
        run: ${{ inputs.command }} -coverprofile=${{ inputs.output-file }} ${{ inputs.scope }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        with:
          name: code-coverage-report
          path: ${{ inputs.output-file }}
          if-no-files-found: error
          retention-days: 1