name: "Go Coverage"

on:
  workflow_call:
    inputs:

      scope:
        description: 'The location to run the command on (defaults to ./...)'
        required: false
        type: string
        default: ./...

permissions: {}

jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ff9d14760a73102d9fa2f47131624137f50ead8
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443

      - uses: bytemare/actions/init-go@b7e5199ae151599349287076bcccf7014ae98d99
        with:
          go-mod: ${{ inputs.go-mod }}

      - name: Run coverage
        id: cover
        run: ${{ inputs.command }} -coverprofile=${{ inputs.output-file }} ${{ inputs.scope }}
