name: golangci-lint

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        description: 'Path to the GolangCI-Lint configuration file'
        type: string
        default: .github/.golangci.yml
      scope:
        required: false
        description: 'Go mod file (defaults to ./go.mod)'
        type: string
        default: ./...
      go-mod:
        required: false
        description: 'Go mod file (defaults to ./go.mod)'
        type: string
        default: ./go.mod

permissions: {}

jobs:
  GolangCI-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6ec6af7d622602bd852df48848f3cae95c760a48
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            raw.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - uses: bytemare/actions/init-go@3bb9abafed30ae2dad9ad9b0232a4a4fe5742067
        with:
          go-mod: ${{ inputs.go-mod }}

      - uses: golangci/golangci-lint-action@b871b4f9de8b829c8d43b0e3bcdf9a8a3f141a3b
        with:
          version: latest
          args: --config=${{ inputs.config-path }} ${{ inputs.scope }}
