#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2025 Daniel Bourdrez. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree or at
# https://spdx.org/licenses/MIT.html
#

name: Linting

on:
  workflow_call:
    inputs:
      golangci-config-path:
        required: false
        description: "Path to the golangci-lint configuration file"
        type: string
        default: ./.github/.golangci.yaml
      scope:
        required: false
        description: "Scope to lint"
        type: string
        default: ./...

permissions: {}

jobs:
  DoNotSubmit:
    name: Do Not Submit
    permissions:
      contents: read
    uses: ./.github/workflows/do-not-submit.yaml

  GolangCILint:
    name: GolangCI Lint
    permissions:
      contents: read
    uses: ./.github/workflows/golangci-lint.yaml
    with:
      config-path: ${{inputs.golangci-config-path}}
      scope: ${{inputs.scope}}