#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2025 Daniel Bourdrez. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree or at
# https://spdx.org/licenses/MIT.html
#

name: Release Suite

on:
  workflow_call:
    inputs:
      slsa:
        description: 'Run the SLSA release workflow'
        required: false
        type: boolean
        default: true
      sign-blobs:
        description: 'Sign release artifacts when running SLSA'
        required: false
        type: boolean
        default: true
      create-release:
        description: 'Create or update the GitHub Release when running SLSA'
        required: false
        type: boolean
        default: true
      extended-metadata:
        description: 'Produce additional metadata in the packaging step'
        required: false
        type: boolean
        default: false
      dry-run:
        description: 'Run the SLSA workflow in dry-run mode'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write
  attestations: write
  actions: read
  security-events: write

jobs:
  SLSA:
    if: ${{ inputs.slsa }}
    uses: ./.github/workflows/slsa.yaml
    with:
      sign_blobs: ${{ inputs['sign-blobs'] }}
      create_release: ${{ inputs['create-release'] }}
      extended_metadata: ${{ inputs['extended-metadata'] }}
      dry_run: ${{ inputs['dry-run'] }}
