name: Code Scanning

on:
  workflow_call:
    inputs:
      sonar-configuration:
        required: true
        description: "Path to the configuration file"
        type: string
      coverage-command:
        description: 'The command to use to run the tests (defaults to go test -v -race -covermode=atomic -coverpkg=./...)'
        required: false
        type: string
        default: go test -v -race -covermode=atomic -coverpkg=./...
      coverage-output-file:
        description: 'The output file name to store the coverage results in (defaults to .github/coverage.out)'
        required: false
        type: string
        default: .github/coverage.out
      coverage-scope:
        description: 'The location to run the command on (defaults to ./...)'
        required: false
        type: string
        default: ./...
      go-mod:
        description: 'Go mod file'
        required: false
        type: string
        default: ./go.mod
    secrets:
      github:
        required: true
      sonar:
        required: true
      codecov:
        required: true
      semgrep:
        required: true

permissions: {}

jobs:
  Semgrep:
    runs-on: ubuntu-22.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.semgrep }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - run: semgrep ci

  Codecov:
    runs-on: ubuntu-latest
    needs: Cover
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6d3c2fe731c8f225990c8018cb71c337c0d9dfcd
        with:
          egress-policy: audit

      - name: Init go
        uses: bytemare/actions/init-go@b5df0586e4b3930b4302e3053774e030afdf17c9
        with:
          go-mod: ${{ inputs.go-mod }}

      - name: Code Coverage
        shell: bash
        run: ${{ inputs.coverage-command }} -coverprofile=${{ inputs.coverage-output-file }} ${{ inputs.coverage-scope }}

      - uses: bytemare/actions/codecov@8babe250116e9e79ce4420a04304661ac9caf73f
        env:
          CODECOV_TOKEN: ${{ secrets.codecov }}
        with:
          coverage-report: ${{ needs.Cover.outputs.coverage-output-file }}

  Sonar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6d3c2fe731c8f225990c8018cb71c337c0d9dfcd
        with:
          egress-policy: audit
      - name: Init go
        uses: bytemare/actions/init-go@b5df0586e4b3930b4302e3053774e030afdf17c9
        with:
          go-mod: ${{ inputs.go-mod }}

      - name: Code Coverage
        shell: bash
        run: ${{ inputs.coverage-command }} -coverprofile=${{ inputs.coverage-output-file }} ${{ inputs.coverage-scope }}
        
      - uses: bytemare/actions/sonar-scan@8babe250116e9e79ce4420a04304661ac9caf73f
        env:
          GITHUB_TOKEN: ${{ secrets.github }}
          SONAR_TOKEN: ${{ secrets.sonar }}
        with:
          configuration: ${{ inputs.sonar-configuration }}
          go-mod: ${{ inputs.go-mod }}
