name: Code Scanning

on:
  workflow_call:
    inputs:
      sonar-configuration:
        required: true
        description: "Path to the configuration file"
        type: string
      coverage-command:
        description: 'The command to use to run the tests (defaults to go test -v -race -covermode=atomic -coverpkg=./...)'
        required: false
        type: string
        default: go test -v -race -covermode=atomic -coverpkg=./...
      coverage-output-file:
        description: 'The output file name to store the coverage results in (defaults to coverage.out)'
        required: false
        type: string
        default: coverage.out
      go-mod:
        description: 'Go mod file'
        required: false
        type: string
        default: ./go.mod
    secrets:
      github:
        required: true
      sonar:
        required: true
      codecov:
        required: true
      semgrep:
        required: true

permissions: {}

jobs:
  Cover:
    uses: ./.github/workflows/coverage-go.yml
    with:
      command: ${{ inputs.coverage-command }}
      output-file: ${{ inputs.coverage-output-file }}

  Semgrep:
    runs-on: ubuntu-22.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.semgrep }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - run: semgrep ci

  Codecov:
    runs-on: ubuntu-latest
    needs: Cover
    steps:
      - name: Download code coverage report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
        with:
          name: ${{ needs.Cover.outputs.coverage-output-artefact }}

      - uses: bytemare/actions/codecov@b7e5199ae151599349287076bcccf7014ae98d99
        env:
          CODECOV_TOKEN: ${{ secrets.codecov }}
        with:
          coverage-report: ${{ needs.Cover.outputs.coverage-output-file }}

  Sonar:
    runs-on: ubuntu-latest
    needs: Cover
    permissions:
      contents: read
    steps:
      - name: Download code coverage report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
        with:
          name: ${{ needs.Cover.outputs.coverage-output-artefact }}

      - uses: bytemare/actions/sonar-scan@02fd456bc430f784b641ca39ac950a4e711c392a
        env:
          GITHUB_TOKEN: ${{ secrets.github }}
          SONAR_TOKEN: ${{ secrets.sonar }}
        with:
          configuration: ${{ inputs.sonar-configuration }}
          coverage: /home/runner/work/workflows/workflows/${{ needs.Cover.outputs.coverage-output-file }}