#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2025 Daniel Bourdrez. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree or at
# https://spdx.org/licenses/MIT.html
#

name: Code Scanning

on:
  workflow_call:
    inputs:
      sonar-configuration:
        required: true
        description: "Path to the configuration file"
        type: string
    secrets:
      github:
        required: true
      sonar:
        required: true
      codecov:
        required: true
      semgrep:
        required: true

permissions: {}

jobs:
  Govulncheck:
    permissions:
      contents: read
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
    uses: ./.github/workflows/govulncheck.yaml

  Dependency-Review:
    name: Dependency Review
    permissions:
      contents: read
    uses: ./.github/workflows/dependency-review.yaml

  Semgrep:
    permissions:
      contents: read
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
    uses: ./.github/workflows/semgrep.yaml
    secrets:
      semgrep: ${{ secrets.semgrep }}

  Codecov:
    uses: ./.github/workflows/codecov.yaml
    secrets:
      codecov: ${{ secrets.codecov }}

  SonarQube:
    permissions:
      contents: read
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
    uses: ./.github/workflows/sonarqube.yaml
    secrets:
      github: ${{ secrets.github }}
      sonar: ${{ secrets.sonar }}
    with:
      configuration: ${{ inputs.sonar-configuration }}
