name: Code Scanning

on:
  workflow_call:
    inputs:
      sonar-configuration:
        required: true
        description: "Path to the configuration file"
        type: string
      coverage-command:
        description: 'The command to use to run the tests (defaults to go test -v -race -covermode=atomic -coverpkg=./...)'
        required: false
        type: string
        default: go test -v -race -covermode=atomic -coverpkg=./...
      coverage-output-file:
        description: 'The output file name to store the coverage results in (defaults to coverage.out)'
        required: true
        type: string
        default: coverage.out
      coverage-scope:
        description: 'The location to run the command on (defaults to ./...)'
        required: false
        type: string
        default: ./...
      go-mod:
        description: 'Go mod file'
        required: false
        type: string
        default: ./go.mod
    secrets:
      github:
        required: true
      sonar:
        required: true
      codecov:
        required: true
      semgrep:
        required: true

permissions: {}

jobs:
  Dependency-Review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443
            api.github.com:443
            api.securityscorecards.dev:443
            github.com:443

      - name: 'Checkout Repository'
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@6ea3b24563819b02be6332d9a462499780efd5d1
        with:
          base-ref: ${{ github.event.pull_request.base.sha || 'main' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}

  Semgrep:
    runs-on: ubuntu-22.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.semgrep }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repo
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc
      - run: semgrep ci

  Codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: audit

      - name: Init go
        uses: bytemare/actions/init-go@bdd15d7ad800e184306260e77e21763da919bc17
        with:
          go-mod: ${{ inputs.go-mod }}

      - name: Code Coverage
        shell: bash
        run: ${{ inputs.coverage-command }} -coverprofile=${{ inputs.coverage-output-file }} ${{ inputs.coverage-scope }}

      - uses: bytemare/actions/codecov@bdd15d7ad800e184306260e77e21763da919bc17
        env:
          CODECOV_TOKEN: ${{ secrets.codecov }}
        with:
          coverage-report: ${{ needs.Cover.outputs.coverage-output-file }}

  Sonar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: bytemare/actions/sonar-scan@bdd15d7ad800e184306260e77e21763da919bc17
        env:
          GITHUB_TOKEN: ${{ secrets.github }}
          SONAR_TOKEN: ${{ secrets.sonar }}
        with:
          configuration: ${{ inputs.sonar-configuration }}
          coverage-output-file: ${{ inputs.coverage-output-file }}
          go-mod: ${{ inputs.go-mod }}
