name: Semgrep

on:
  workflow_call:
    secrets:
      semgrep:
        required: true

permissions: {}

jobs:
  Semgrep:
    permissions:
      contents: read
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
    runs-on: ubuntu-24.04
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repo
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run Semgrep
        run: semgrep ci --no-suppress-errors
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.semgrep }}

      - name: "Upload SARIF results to GitHub's code scanning dashboard"
        uses: github/codeql-action/upload-sarif@e0ea141027937784e3c10ed1679e503fcc2245bc
        with:
          sarif_file: semgrep.sarif
        if: always()