name: Test Go

on:
  workflow_call:
    inputs:
      command:
        description: 'The command to use to run the tests (defaults to go test -v -vet=all ./...)'
        required: false
        type: string
        default: go test -v -vet=all ./...
      version:
        description: 'The Go version to use'
        required: false
        type: string

permissions: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@29e9ae12297382bde04e940b27e0638029f9f3cd
        with:
          egress-policy: audit

      - name: Init go
        uses: bytemare/actions/init-go@f557d070fea2f5182be2be66ca7e8546785ed3c1
        with:
          version: ${{ inputs.version }}

      - name: Run Tests
        run: ${{ inputs.command }}
