name: Test Go

on:
  workflow_call:
    inputs:
      command:
        description: 'The command to use to run the tests (defaults to go test -v -vet=all ./...)'
        required: false
        type: string
        default: go test -v -vet=all ./...
      version:
        description: 'The Go version to use'
        required: false
        type: string

permissions: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Init go
        uses: bytemare/actions/init-go@2a408fa01e57869bc8e92ded1963b07a602b2500
        with:
          go-version: ${{ inputs.version }}

      - name: Run Tests
        run: ${{ inputs.command }}
