name: Test Go

on:
  workflow_call:
    inputs:
      command:
        description: 'The command to use to run the tests (defaults to go test -v -vet=all ./...)'
        required: false
        type: string
        default: go test -v -vet=all ./...
      version:
        description: 'The Go version to use'
        required: false
        type: string

permissions: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Init go
        uses: bytemare/actions/init-go@f134a880e99461ef1ee112e41b9206901412c3ff
        with:
          go-version: ${{ inputs.version }}

      - name: Run Tests
        run: ${{ inputs.command }}
