name: Test Go

on:
  workflow_call:
    inputs:
      command:
        description: 'The command to use to run the tests (defaults to go test -v -vet=all ./...)'
        required: false
        type: string
        default: go test -v -vet=all ./...
      version:
        description: 'The Go version to use'
        required: false
        type: string

permissions: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@951b48540b429070694bc8abd82fd6901eb123ca
        with:
          egress-policy: audit

      - name: Init go
        uses: bytemare/actions/init-go@de9874d3f9ede44c3e4c814e1b60116aaa33bc4f
        with:
          version: ${{ inputs.version }}

      - name: Run Tests
        run: ${{ inputs.command }}
