name: Test Go

on:
  workflow_call:
    inputs:
      command:
        description: 'The command to use to run the tests (defaults to go test -v -vet=all ./...)'
        required: false
        type: string
        default: go test -v -vet=all ./...
      version:
        description: 'The Go version to use'
        required: false
        type: string

permissions: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Init go
        uses: bytemare/actions/init-go@c50a6904f8086ab63fc28a1c9a7302ec92feb4f6
        with:
          go-version: ${{ inputs.version }}

      - name: Run Tests
        run: ${{ inputs.command }}
