name: Test Go

on:
  workflow_call:
    inputs:
      command:
        description: 'The command to use to run the tests (defaults to go test -v -vet=all ./...)'
        required: false
        type: string
        default: go test -v -vet=all ./...
      version:
        description: 'The Go version to use'
        required: false
        type: string

permissions: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Init go
        uses: bytemare/actions/init-go@0ba6fa75807a32bdccbe0bd102a8a37205994562
        with:
          go-version: ${{ inputs.version }}

      - name: Run Tests
        run: ${{ inputs.command }}
