name: Code Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Every 3 days at 7 a.m.
    - cron: '0 7 */3 * *'

permissions: {}

jobs:
  Lint:
    permissions:
      contents: read
    uses: ./.github/workflows/golangci-lint.yml
    with:
      config-path: ./.github/golangci.yml
      scope: ./...

  Analyze:
    permissions:
      contents: read
    uses: ./.github/workflows/scan-go.yml
    with:
      sonar-configuration: .github/sonar-project.properties
      coverage-output-file: coverage.out
    secrets:
      github: ${{ secrets.GITHUB_TOKEN }}
      sonar: ${{ secrets.SONAR_TOKEN }}
      codecov: ${{ secrets.CODECOV_TOKEN }}
      semgrep: ${{ secrets.SEMGREP_APP_TOKEN }}